# Generated by Django 2.2.7 on 2019-11-23 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.CharField(max_length=30, verbose_name='编号')),
                ('position', models.CharField(max_length=30, verbose_name='坐标')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(max_length=200, verbose_name='附加描述')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
            },
        ),
        migrations.CreateModel(
            name='Node_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.TimeField(default=None, verbose_name='采集时间')),
                ('collect_date', models.DateField(default=None, verbose_name='采集日期')),
                ('collect_datatime', models.DateTimeField(default=None, verbose_name='采集日期时间')),
                ('temperature', models.FloatField(verbose_name='温度/℃')),
                ('soil_humidity', models.FloatField(verbose_name='土壤湿度/%')),
                ('air_humidity', models.FloatField(verbose_name='空气湿度/%')),
                ('oxygen', models.FloatField(verbose_name='氧气浓度/%')),
                ('carbon_dioxide', models.FloatField(verbose_name='二氧化碳浓度/%')),
                ('battery', models.FloatField(verbose_name='电池电量/%')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect_data.Sensor_node', verbose_name='节点')),
            ],
            options={
                'verbose_name': '节点收集的数据',
                'verbose_name_plural': '节点收集的数据',
            },
        ),
    ]
