# Generated by Django 2.2.7 on 2019-11-23 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node_data',
            old_name='collect_datatime',
            new_name='collect_datetime',
        ),
    ]
